# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesignerUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 880)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Form.setFont(font)
        Form.setMouseTracking(False)
        Form.setAcceptDrops(False)
        self.instructionButton = QtWidgets.QPushButton(Form)
        self.instructionButton.setGeometry(QtCore.QRect(1250, 20, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.instructionButton.setFont(font)
        self.instructionButton.setObjectName("instructionButton")
        self.label_show_camera = QtWidgets.QLabel(Form)
        self.label_show_camera.setGeometry(QtCore.QRect(0, 0, 1536, 960))
        self.label_show_camera.setAutoFillBackground(True)
        self.label_show_camera.setText("")
        self.label_show_camera.setObjectName("label_show_camera")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1200, 720, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(1200, 770, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(1340, 770, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1270, 580, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.real_label = QtWidgets.QLabel(Form)
        self.real_label.setGeometry(QtCore.QRect(1250, 110, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.real_label.setFont(font)
        self.real_label.setObjectName("real_label")
        self.save_parameter_button = QtWidgets.QPushButton(Form)
        self.save_parameter_button.setGeometry(QtCore.QRect(1420, 640, 50, 50))
        self.save_parameter_button.setMaximumSize(QtCore.QSize(50, 50))
        self.save_parameter_button.setAutoFillBackground(True)
        self.save_parameter_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("picture/save2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_parameter_button.setIcon(icon)
        self.save_parameter_button.setIconSize(QtCore.QSize(50, 50))
        self.save_parameter_button.setAutoRepeatInterval(300)
        self.save_parameter_button.setObjectName("save_parameter_button")
        self.width_lineEdit = QtWidgets.QLineEdit(Form)
        self.width_lineEdit.setGeometry(QtCore.QRect(1250, 720, 61, 31))
        self.width_lineEdit.setObjectName("width_lineEdit")
        self.height_lineEdit = QtWidgets.QLineEdit(Form)
        self.height_lineEdit.setGeometry(QtCore.QRect(1250, 770, 61, 31))
        self.height_lineEdit.setObjectName("height_lineEdit")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(1340, 720, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.y_lineEdit = QtWidgets.QLineEdit(Form)
        self.y_lineEdit.setGeometry(QtCore.QRect(1400, 720, 61, 31))
        self.y_lineEdit.setObjectName("y_lineEdit")
        self.x_lineEdit = QtWidgets.QLineEdit(Form)
        self.x_lineEdit.setGeometry(QtCore.QRect(1400, 770, 61, 31))
        self.x_lineEdit.setObjectName("x_lineEdit")
        self.coxial_textEdit = QtWidgets.QTextEdit(Form)
        self.coxial_textEdit.setGeometry(QtCore.QRect(1210, 650, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.coxial_textEdit.setFont(font)
        self.coxial_textEdit.setObjectName("coxial_textEdit")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(1260, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.thickness_lineEdit = QtWidgets.QLineEdit(Form)
        self.thickness_lineEdit.setGeometry(QtCore.QRect(1360, 250, 51, 31))
        self.thickness_lineEdit.setObjectName("thickness_lineEdit")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(1200, 90, 281, 20))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("picture/greenline.png"))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(1200, 310, 291, 20))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("picture/greenline.png"))
        self.label_13.setObjectName("label_13")
        self.camera_width_lineEdit = QtWidgets.QLineEdit(Form)
        self.camera_width_lineEdit.setGeometry(QtCore.QRect(1250, 830, 61, 31))
        self.camera_width_lineEdit.setObjectName("camera_width_lineEdit")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(1190, 830, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.camera_height_lineEdit = QtWidgets.QLineEdit(Form)
        self.camera_height_lineEdit.setGeometry(QtCore.QRect(1400, 830, 61, 31))
        self.camera_height_lineEdit.setObjectName("camera_height_lineEdit")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(1330, 830, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(1190, 530, 291, 20))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("picture/greenline.png"))
        self.label_14.setObjectName("label_14")
        self.real_label_2 = QtWidgets.QLabel(Form)
        self.real_label_2.setGeometry(QtCore.QRect(1260, 330, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.real_label_2.setFont(font)
        self.real_label_2.setObjectName("real_label_2")
        self.track_start_button = QtWidgets.QPushButton(Form)
        self.track_start_button.setGeometry(QtCore.QRect(1310, 400, 50, 49))
        self.track_start_button.setMaximumSize(QtCore.QSize(50, 50))
        self.track_start_button.setAutoFillBackground(True)
        self.track_start_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("picture/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.track_start_button.setIcon(icon1)
        self.track_start_button.setIconSize(QtCore.QSize(50, 50))
        self.track_start_button.setAutoRepeatInterval(300)
        self.track_start_button.setObjectName("track_start_button")
        self.track_textEdit = QtWidgets.QTextEdit(Form)
        self.track_textEdit.setGeometry(QtCore.QRect(1250, 470, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.track_textEdit.setFont(font)
        self.track_textEdit.setObjectName("track_textEdit")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(1260, 170, 164, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.real_start_button = QtWidgets.QPushButton(self.layoutWidget)
        self.real_start_button.setMaximumSize(QtCore.QSize(50, 50))
        self.real_start_button.setAutoFillBackground(True)
        self.real_start_button.setText("")
        self.real_start_button.setIcon(icon1)
        self.real_start_button.setIconSize(QtCore.QSize(50, 50))
        self.real_start_button.setAutoRepeatInterval(300)
        self.real_start_button.setObjectName("real_start_button")
        self.horizontalLayout.addWidget(self.real_start_button)
        self.real_shizi_button = QtWidgets.QPushButton(self.layoutWidget)
        self.real_shizi_button.setMaximumSize(QtCore.QSize(50, 50))
        self.real_shizi_button.setAutoFillBackground(True)
        self.real_shizi_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("picture/shizi2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.real_shizi_button.setIcon(icon2)
        self.real_shizi_button.setIconSize(QtCore.QSize(50, 50))
        self.real_shizi_button.setAutoRepeatInterval(300)
        self.real_shizi_button.setObjectName("real_shizi_button")
        self.horizontalLayout.addWidget(self.real_shizi_button)
        self.real_clear_button = QtWidgets.QPushButton(self.layoutWidget)
        self.real_clear_button.setMaximumSize(QtCore.QSize(50, 50))
        self.real_clear_button.setAutoFillBackground(True)
        self.real_clear_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("picture/222.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.real_clear_button.setIcon(icon3)
        self.real_clear_button.setIconSize(QtCore.QSize(50, 50))
        self.real_clear_button.setAutoRepeatInterval(300)
        self.real_clear_button.setObjectName("real_clear_button")
        self.horizontalLayout.addWidget(self.real_clear_button)
        self.label_show_camera.raise_()
        self.instructionButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.real_label.raise_()
        self.save_parameter_button.raise_()
        self.width_lineEdit.raise_()
        self.height_lineEdit.raise_()
        self.label_4.raise_()
        self.y_lineEdit.raise_()
        self.x_lineEdit.raise_()
        self.coxial_textEdit.raise_()
        self.label_10.raise_()
        self.thickness_lineEdit.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.camera_width_lineEdit.raise_()
        self.label_6.raise_()
        self.camera_height_lineEdit.raise_()
        self.label_7.raise_()
        self.label_14.raise_()
        self.real_label_2.raise_()
        self.track_start_button.raise_()
        self.track_textEdit.raise_()
        self.layoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.instructionButton.setText(_translate("Form", "Instructions"))
        self.label.setText(_translate("Form", "Width："))
        self.label_2.setText(_translate("Form", "Height："))
        self.label_3.setText(_translate("Form", "X Site："))
        self.label_5.setText(_translate("Form", "Coaxial Calibration"))
        self.real_label.setText(_translate("Form", " Real-time Guidance"))
        self.width_lineEdit.setText(_translate("Form", "50"))
        self.height_lineEdit.setText(_translate("Form", "50"))
        self.label_4.setText(_translate("Form", "Y Site："))
        self.y_lineEdit.setText(_translate("Form", "50"))
        self.x_lineEdit.setText(_translate("Form", "50"))
        self.coxial_textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_10.setText(_translate("Form", "Thickness:"))
        self.thickness_lineEdit.setText(_translate("Form", "50"))
        self.camera_width_lineEdit.setText(_translate("Form", "50"))
        self.label_6.setText(_translate("Form", "Width_cut:"))
        self.camera_height_lineEdit.setText(_translate("Form", "50"))
        self.label_7.setText(_translate("Form", "Height_cut:"))
        self.real_label_2.setText(_translate("Form", "Annotations Tracking"))
        self.track_textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
